module.exports = {
    'black':        [ 'black' ],
    'grey':         [ 'grey', 'gray', 'silver', 'darkgray', 'darkgrey', 'darkslategray', 'darkslategrey', 'dimgray', 'dimgrey', 'gainsboro', 
                        'lightgray', 'lightgrey', 'lightslategray', 'lightslategrey', 'slategray', 'slategrey' ],
    'brown':        [ 'brown', 'antiquewhite', 'beige', 'bisque', 'blanchedalmond', 'burlywood', 'chocolate', 'coral', 'cornsilk', 'darkgoldenrod',
                        'darkkhaki', 'goldenrod', 'khaki', 'lightgoldenrodyellow', 'linen', 'moccasin', 'navajowhite', 'papayawhip', 'peachpuff', 
                        'peru', 'rosybrown', 'saddlebrown', 'sandybrown', 'sienna', 'tan', 'wheat' ],
    'white':        [ 'white', 'floralwhite', 'ghostwhite', 'honeydew', 'ivory', 'mintcream', 'oldlace', 'seashell', 'snow', 'whitesmoke' ],
    'red':          [ 'red', 'maroon', 'crimson', 'darkorange', 'darkred', 'darksalmon', 'firebrick', 'indianred', 'lightcoral', 'lightsalmon', 
                        'mistyrose', 'orange', 'orangered', 'salmon', 'tomato' ],
    'purple':       [ 'purple', 'fuchsia', 'darkmagenta', 'darkorchid', 'darkviolet', 'deeppink', 'hotpink', 'lavenderblush', 'lightpink', 'magenta', 
                        'mediumorchid', 'mediumpurple', 'mediumvioletred', 'orchid', 'palevioletred', 'pink', 'plum', 'thistle', 'violet', 'violetred' ],
    'green':        [ 'green', 'lime', 'olive', 'cadetblue', 'chartreuse', 'darkgreen', 'darkolivegreen', 'darkseagreen', 'forestgreen', 'greenyellow', 
                        'lawngreen', 'lightgreen', 'lightseagreen', 'limegreen', 'mediumaquamarine', 'mediumseagreen', 'mediumspringgreen', 'olivedrab', 
                        'palegoldenrod', 'palegreen', 'seagreen', 'springgreen', 'teal', 'yellowgreen' ],
    'yellow':       [ 'yellow', 'gold', 'lemonchiffon', 'lightyellow', 'lightgoldenrod' ],
    'blue':         [ 'blue', 'navy', 'teal', 'aqua', 'aliceblue', 'aquamarine', 'azure', 'blueviolet', 'cornflowerblue', 'cyan', 'darkblue', 
                        'darkcyan', 'darkslateblue', 'darkturquoise', 'deepskyblue', 'dodgerblue', 'indigo', 'lavender', 'lightblue', 'lightcyan',
                        'lightskyblue', 'lightsteelblue', 'mediumblue', 'mediumslateblue', 'mediumturquoise', 'midnightblue', 'navy', 'paleturquoise', 
                        'powderblue', 'royalblue', 'skyblue', 'slateblue', 'steelblue', 'turquoise', 'lightslateblue' ]
}